<?php

declare(strict_types=1);

require_once dirname(__DIR__, 2) . '/shared/helpers/helpers.php';
require_once dirname(__DIR__, 2) . '/shared/security/csrf.php';
require_once dirname(__DIR__, 2) . '/shared/middleware/authorization.php';
require_once dirname(__DIR__, 2) . '/auth/authService.php';
require_once __DIR__ . '/historyService.php';

require_admin();
$complaintId = filter_var($_GET['complaint_id'] ?? null, FILTER_VALIDATE_INT, [
    'options' => ['min_range' => 1],
]);
$complaintId = $complaintId === false ? null : $complaintId;

try {
    $history = get_admin_history($complaintId);
} catch (Throwable $exception) {
    error_log($exception->getMessage());
    http_response_code(503);
    exit('Complaint history is temporarily unavailable.');
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Complaint History | Complaint Management System</title>
    <link rel="stylesheet" href="../../../assets/css/main.css">
</head>
<body>
    <?php require dirname(__DIR__) . '/adminNavigation.php'; ?>
    <main class="page-shell">
        <section class="page-heading">
            <p class="eyebrow">Administration</p>
            <h1>Complaint history</h1>
            <p>Read-only audit records generated by complaint operations.</p>
        </section>
        <section class="content-card filter-card">
            <form method="get" class="admin-filter-form">
                <label for="complaint_id">Complaint ID</label>
                <input id="complaint_id" name="complaint_id" type="number" min="1" value="<?= $complaintId === null ? '' : e((string) $complaintId) ?>">
                <button type="submit">Filter</button>
                <a href="historyList.php">Clear</a>
            </form>
        </section>
        <?php if ($history === []): ?>
            <section class="content-card empty-state"><h2>No history found</h2><p>No audit records match this filter.</p></section>
        <?php else: ?>
            <section class="content-card table-card"><div class="table-wrapper"><table>
                <thead><tr><th>Complaint</th><th>Action</th><th>Performed by</th><th>Status change</th><th>Assignment change</th><th>Description</th><th>Timestamp</th></tr></thead>
                <tbody>
                <?php foreach ($history as $entry): ?>
                    <tr>
                        <td>#<?= e((string) $entry['complaint_id']) ?></td>
                        <td><?= e($entry['action']) ?></td>
                        <td><?= e($entry['performed_by_name']) ?></td>
                        <td><?= e(($entry['old_status'] ?? 'none') . ' to ' . ($entry['new_status'] ?? 'none')) ?></td>
                        <td><?= e(($entry['assigned_from_name'] ?? 'Unassigned') . ' to ' . ($entry['assigned_to_name'] ?? 'Unassigned')) ?></td>
                        <td><?= e($entry['description']) ?></td>
                        <td><?= e($entry['created_at']) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table></div></section>
        <?php endif; ?>
    </main>
</body>
</html>
